env:
  browser: true
  node: true
  es2022: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  ignorePatterns:
    - build/
  sourceType: module
rules:
  array-bracket-spacing:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  arrow-parens: error
  no-confusing-arrow: error
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
