name: Build
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Commit results
        # Commit is not executed if there were no changes.
        run: |
          git config user.name github-actions
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update data files"
          git push
