name: Update data files
on:
  schedule:
    # Every day @ midnight.
    - cron: "0 0 * * *"
jobs:
  main:
    name: Update data files
    runs-on: ubuntu-latest
    steps:
      - uses: kentr/actions/checkout-setup-node@main
        with:
          node-version: "16"
      - name: Build
        run: npm run build
      - name: Commit results
        # Commit is not executed if there were no changes.
        run: |
          git config user.name github-actions
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update data files"
          git push
